### ISSUE TITLE
espeak-ng.data cannot be found

### ISSUE THREAD

**Issue by allen2peace** [echogarden-project/echogarden#48]
Hello, when I call the Echogarden.align method, I get the following error:

> Create alignment reference with eSpeak.. package error: [Error: ENOENT: no such file or directory, open 'myProjectPath/.next/server/vendor-chunks/espeak-ng.data'] {
   errno: -2,
   code: 'ENOENT',
   syscall: 'open',
   path: 'myProjectPath/.next/server/vendor-chunks/espeak-ng.data'
}

What is the reason for this?

Where is the file espeak-ng.data generated? Which directory does it need to be placed in?

**Comment by rotemdan** [comment]
The file isn't generated. It's the main eSpeak-NG data file that contains all the voices and other information. It is loaded by the Emscripten version of eSpeak-NG.

The code that resolves its path is included the `eSpeak-NG` C codebase itself (I added it in my fork - since otherwise it would be broken):

It is located in [`emscripten/pre.js`](https://github.com/echogarden-project/espeak-ng/blob/fork/emscripten/pre.js):
```js
Module['locateFile'] = function (path, prefix) {
	//console.log("locateFile:", path, prefix)
	//console.log("__dirname:", __dirname)

	if (path == "espeak-ng.data") {
		return __dirname + "/" + "espeak-ng.data"
	} else {
		return prefix + path
	}
}
```

This is extra JavaScript code that is needed to ensure that the file is properly located. It is prepended to `espeak-ng.cjs` during Emscripten compilation.

The Emscripten compiled code is loaded through the `@echogarden/espeak-ng-emscripten` npm package. It is not a part of the main `echogarden` repository.

`__dirname` should normally resolve to:

```
myProjectPath/node_modules/espeak-ng-emscripten/espeak-ng.data
```

Seems like in your installation `__dirname` is instead resolving to 
```
myProjectPath/.next/server/vendor-chunks/`
```

The Node.js documentation for `__dirname` says:
> The directory name of the current module. This is the same as the [path.dirname()](https://nodejs.org/docs/latest/api/path.html#pathdirnamepath) of the [__filename](https://nodejs.org/docs/latest/api/modules.html#__filename).

Here is the directory structure in `node_modules/espeak-ng-emscripten`:
![Screenshot_4](https://github.com/echogarden-project/echogarden/assets/8589488/f3e76b72-49e4-4f5f-8450-1314d287b702)

Something about the way modules are loaded in your project is resolving `__dirname` in a non-standard way? Maybe it's because it is bundled in some way? I'll need more information to investigate further.

**Comment by allen2peace** [comment]
I am using it in a `Nextjs` project. In fact, my project has the directory in your screenshot, but I don’t know why `__dirname` points to the `.next` directory.

![QQ截图20240423135617](https://github.com/echogarden-project/echogarden/assets/6928331/cab84498-729c-4f81-8608-e7acae1e52e0)

I've done some searching, but I still can't figure out the reason. 

How can I modify it so that `__dirname` points to `myProjectPath/node_modules/@echogarden/espeak-ng-emscripten`?

**Comment by rotemdan** [comment]
From what I searched, `vendor-chunks` is a path used by webpack. 

In any case, trying to bundle `echogarden` in any form is extremely likely to fail on many places since there are large numbers of extra data and native code, including JSON and binary data files, shared libraries, WASM and WASI files, binaries, etc. in its package dependencies. For example `onnruntime-node` alone has more than 100MB of binaries and native shared libraries for various architectures.

I don't know how exactly how `Next.js` is trying to bundle `echogarden`. If it's for the web then of course that wouldn't work (even if it did, it would be at least 300MB of code and data). If it's for the server side then it also wouldn't work, and is also mostly unnecessary. Also, compiling and bundling an execution via `electron` would be very difficult as well, but that's not really related.

**Comment by allen2peace** [comment]
Thank you for your detailed reply.

I am trying to use the functions provided by the `echogarden` library in my website project, but so far it has not been configured properly. 

Do you mean that `echogarden` cannot run on the web project? 

If so, are there any other similar libraries to recommend?

**Comment by rotemdan** [comment]
It can't run on the web. It runs in Node.js only.

* It uses native `ffmpeg` executables to for codec conversions. Although a WASM version of FFMpeg was included in the past, I removed it since was very slow and hardly used.
* It downloads models and voices from a remote repository (currently totaling 50GB) and stores them locally. Replicating that on the web means basically creating a virtual file system. That's not very simple.
* It depends `onnxruntime-node`, which only runs in Node.js, although there is a variant, called [onnxruntime-web](https://www.npmjs.com/package/onnxruntime-web), but is so slow on CPU it would be impractical to use it, for, say running Whisper speech recognition models.
* Memory requirements can easily get several gigabytes. For computing alignment using DTW for a long audio - say an hour or more, it can get even to 10GB or more. That's not very web-friendly.

Even if it was possible to have a web port for some of the functionality, that would require a large amount of effort, possibly even several months of work, and the resulting module would be slow, lacking in functionality (can't write to disk, can't easily write multiple files, etc.), and a large download overall (at least, say 50MB with extreme effort to reduce its size). Also it would have large memory footprint - for the very least 1GB when running speech models, and may run into limits posed by web browsers on resource allocation.

It's possible there are tools that provide a very small part of the functionality on the web, but I don't know if they would perform it with the same quality. Performing speech-to-transcript alignment in the browser, rather than on a server, is possible, and I've actually implemented that before, but it has very specific use cases and it isn't clear whether it's worth the effort to implement, (also, eSpeak-NG WASM port, which is required for the simplest approach, is 17MB by itself, so that would be the absolute minimum uncompressed download size).

**Comment by an-lee** [comment]
I'm encountering the same problem after upgrading Echogarden to version 2.0.0.

```
package error: [Error: ENOENT: no such file or directory, open 'home/an-lee/projects/everyone-can-use-english/enjoy/node_modules/@echogarden/espeak-ng-emscripten/espeak-ng.data'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'home/an-lee/projects/everyone-can-use-english/enjoy/node_modules/@echogarden/espeak-ng-emscripten/espeak-ng.data'
}
```

I believe the correct path should be `/home/...`, as the issue seems to stem from the missing `/` at the beginning.

I tried downgrading to version 1.8.7, and the problem is gone.

@rotemdan

**Comment by rotemdan** [comment]
Thanks for reporting. On version `2.0.0`, I switched to using an ESM module for `espeak-ng-emscripten`. This means I had to rewrite how it resolves the data file.

The new approach is:
```js
Module['locateFile'] = function (path, prefix) {
	//console.log(`locateFile called, with path: ${path}, prefix: ${prefix}`)

	if (path === "espeak-ng.data") {
		const currentModuleUrl = import.meta.url

		const lastSlashIndex = currentModuleUrl.lastIndexOf('/')

		let directoryPath

		if (currentModuleUrl.startsWith('file:///')) {
			directoryPath = currentModuleUrl.substring(8, lastSlashIndex)
		} else {
			directoryPath = currentModuleUrl.substring(0, lastSlashIndex)
		}

		//console.log(`directoryPath: ${directoryPath}\n\n`)

		return `${directoryPath}/espeak-ng.data`
	} else {
		return `${prefix}${path}`
	}
}
```

What OS are you using? I'll try to reproduce this.

**Comment by an-lee** [comment]
I'm using Ubuntu 24.04.1 LTS.

By the way, the error occurred silently. While it was logged, the error was never thrown. I need to catch these errors and handle them, or else my application just gets stuck.

**Comment by rotemdan** [comment]
Seems like I'm mistakenly taking the first `/` as part of the address, and removing it fro the path. Tried on Ubuntu (WSL):

`test.js`:
```js
console.log(import.meta.url)
```

```
node test.js
file:///home/x/test2/test.js
```

Seems like windows didn't care because it's adding a  `/` that isn't used anyway:

On windows I get:
```
file:///C:/Rotem/Development/experiments/pathTest/test.js
```
So I guess I assumed the extra `/` was unnecessary, but that's only on Windows.

I can try:
```js
		if (currentModuleUrl.startsWith('file://')) {
			directoryPath = currentModuleUrl.substring(7, lastSlashIndex)
		} else {
			directoryPath = currentModuleUrl.substring(0, lastSlashIndex)
		}
```
It's really simple to fix.

I'll publish a fix in a few minutes.

I'm a bit surprised it took a few days until someone actually reported this! I assumed I already tested on Linux (many other changes) but I guess I made this particular change after I tested.

**Comment by rotemdan** [comment]
Turns out windows doesn't like the prefixing `/` in the path:

Trying to read a path like:
```
/C:/Rotem/Development/experiments/pathTest/test.js
```
Gives an error. So now I get why I cut the first `/`

So I'll try to detect the OS and remove the first `/` in Windows:
```
		if (currentModuleUrl.startsWith('file://')) {
			if (process && process.platform === 'win32') {
				directoryPath = currentModuleUrl.substring(8, lastSlashIndex)
			} else {
				directoryPath = currentModuleUrl.substring(7, lastSlashIndex)
			}
		} else {
			directoryPath = currentModuleUrl.substring(0, lastSlashIndex)
		}
```

Just to explain, why am I not doing this in a more robust, reliable way? Because it's intended to be as a cross-platform build, that could work on the web, and the way that Emscripten is calling this callback constrains from any async operations. I cannot load any module. It really limits what I can do. So I have to find the crudest solution that works. Thank you again for reporting.

**Comment by rotemdan** [comment]
I published the fix in `v2.0.2`. I made a basic test and it seems like it works correctly on Windows and on Linux (tested on Ubuntu WSL2).

**Comment by an-lee** [comment]
Thank you!
The new version `v2.0.2` has resolved the problem; I've tested it on Windows, Linux, and macOS.

**Comment by rotemdan** [comment]
Thanks a lot!

I guess was in a hurry so:
```js
if (process && process.platform === 'win32') {
```
Wasn't actually correct. Changed it to:
```js
if (typeof process === 'object' && process.platform === 'win32') {
```

It doesn't really matter that much in practice (it's not designed to run on non-node environements), but I published another version (`v2.0.3`) for that small change.

---

Anyway, if you're already testing things on the new release, you're now also testing the [newly developed native audio playback mechanism](https://github.com/echogarden-project/audio-io) (also adding new features like keyboard navigation, pause/resume, etc.). 

It was especially important for me to get that working on macOS (had to figure out how to deal with the Core Audio API), since due to bugs on Sox for macOS it was using the terrible approach of writing the entire file to disk before playing (can be a huge file if the audio is long). Now it's streaming from memory, with no extra copies, so it can also play virtually unlimited audio durations with no initial load time. 

The new audio output N-API addons are not heavily tested (never tested on Apple Silicon, or any arm64 processor, for example). Let me know if you're experiencing any playback issues (though that would be more relevant to the [`audio-io` issue tracker](https://github.com/echogarden-project/audio-io/issues)).

**Comment by rotemdan** [comment]
[`@echogarden/audio-io`](https://github.com/echogarden-project/audio-io) is a separate package developed developed and released a few weeks ago, which includes 3 native addons that interface with the native audio output on Windows (MME / Wave out), Linux (ALSA) and macOS (Core Audio). It completely replaces `sox` on the command line interface (though sox can still be used if setting `--player=sox`).

It only applies to the Echogarden CLI. It is not used in the API. 

I developed it because I couldn't find any good, well-maintained, potentially low-latency audio playback solution that allowed to stream directly from JavaScript memory, worked cross-platform, and had pre-bundled binaries.

It can be used as an independent library (`npm install @echogarden/audio-io`), though it's currently mostly low-level and requires the exact audio format used by the audio driver (int16 interleaved).

**Comment by rotemdan** [comment]
The issue should be resolved.

(I actually later redid the path resolution all over again, in a more robust way, based on the Windows drive letter pattern, like `file:///x:/`, without importing any modules).

I'll close this for now. Please reopen if it happens again.

**Comment by rotemdan** [comment]
I added a fix in `@echogarden/espeak-ng-emscripten` `v0.3.4`. 

Since it's a minor version increment, the new version should install with the existing `echogarden` version. Likely only re-running `npm install echogarden` is needed to get it upgraded.

Let me know if this fixes the issue. Again thanks for the report.

**Comment by rogerdcarvalho** [comment]
wow your fast haha! So when running npm install again the @echogarden/espeak-ng-emscripten remains 0.3.3... How can I force the update?

**Comment by rotemdan** [comment]
The issue you reported was actually pretty serious. Just imagine how many users may have tried to install `echogarden` in paths containing spaces, got the same error, and never reported.

I'm not sure why it's not updating, it could be that a lock file is preserving the old version.

You can try `npm install @echogarden/espeak-ng-emscripten` or `npm install @echogarden/espeak-ng-emscripten@v0.3.4`. Add `-g` if it's global.

**Comment by rotemdan** [comment]
I'm still getting an error but now:

```
[Error: ENOENT: no such file or directory, open 

'C:\Rotem\DL\test2\node_modules\@echogarden\espeak-ng-emscripten\e\espeak-ng.data'
```

The URI decoding seems to work, but really odd why it adds the `\e\` to the path. I'll need to Investigate more. This is really odd.

**Comment by rotemdan** [comment]
Okay, in `@echogarden/espeak-ng-emscripten` `v0.3.5` I fixed the issue I had before (the slash index wasn't correctly computed on the decoded URI path).

Let me know if `v0.3.5` resolves the issue for you.

**Comment by rogerdcarvalho** [comment]
So after updating I don't see the %20 anymore, but I still get an error. Now I get

package error: [Error: ENOENT: no such file or directory, open 'C:\\Program Files (x86)\\AppName\\resources\\executable\\voice-engine\\node_modules\\@echogarden\\espeak-ng-emscripten\\esp\\espeak-ng.data'] {\n  errno: -4058,\n  code: 'ENOENT',\n  syscall: 'open',\n  path: 'C:\\\\Program Files (x86)\\\\AppName\\\\resources\\\\executable\\\\voice-engine\\\\node_modules\\\\@echogarden\\\\espeak-ng-emscripten\\\\esp\\\\espeak-ng.data'\n}\n"

But if I'm not mistaken, the last time the folder was C:\Program%20Files%20(x86)\AppName\resources\executable\voice-engine\node_modules\@EchoGarden\espeak-ng-emscripten\ whereas now it appears to be C:\Program Files (x86)\AppName\resources\executable\voice-engine\node_modules\@echogarden\espeak-ng-emscripten\**esp**\

On my system there is no esp subfolder, espeak-ng.data is just inside **espeeak-ng-emscripten**

**Comment by rotemdan** [comment]
That's the issue I fixed later in `v0.3.5` the `/esp` occurred because I didn't compute the index of `/` on the decoded URI. Try again in `v0.3.5`.

**Comment by rogerdcarvalho** [comment]
Working perfectly now, thanks so much! And kudos to this library, it is honestly the most expansive set of voice tools I've ever come across and opens up so many possibilities for developers. If there is anything I can do to help you champion echogarden let me know!
